[package]
name = "fourthage-mud-macros"
version = "0.2.0"
edition = "2021"
description = "Helper macros for Fourthage MUD."
license = "MIT"
repository = "https://github.com/jayvalentine/fourthage-mud"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
